# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Client/ClientGRPC/Client.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'Client/ClientGRPC/Client.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x43lient/ClientGRPC/Client.proto\x12\x06\x43lient\"Q\n\x13RegisterRoomRequest\x12\x13\n\x0bRoomAddress\x18\x01 \x01(\t\x12\x13\n\x0bTimeAddress\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\"\'\n\x14RegisterRoomResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"2\n\x0fLoadSongRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tAudioData\x18\x02 \x01(\x0c\"\x12\n\x10LoadSongResponse\"@\n\x10StartSongRequest\x12\x0c\n\x04time\x18\x01 \x01(\x01\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08position\x18\x03 \x01(\x01\"\x13\n\x11StartSongResponse\"\x1f\n\x0fStopSongRequest\x12\x0c\n\x04time\x18\x01 \x01(\x01\"\x12\n\x10StopSongResponse2\x93\x02\n\x06\x43lient\x12I\n\x0cRegisterRoom\x12\x1b.Client.RegisterRoomRequest\x1a\x1c.Client.RegisterRoomResponse\x12=\n\x08LoadSong\x12\x17.Client.LoadSongRequest\x1a\x18.Client.LoadSongResponse\x12@\n\tStartSong\x12\x18.Client.StartSongRequest\x1a\x19.Client.StartSongResponse\x12=\n\x08StopSong\x12\x17.Client.StopSongRequest\x1a\x18.Client.StopSongResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Client.ClientGRPC.Client_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERROOMREQUEST']._serialized_start=42
  _globals['_REGISTERROOMREQUEST']._serialized_end=123
  _globals['_REGISTERROOMRESPONSE']._serialized_start=125
  _globals['_REGISTERROOMRESPONSE']._serialized_end=164
  _globals['_LOADSONGREQUEST']._serialized_start=166
  _globals['_LOADSONGREQUEST']._serialized_end=216
  _globals['_LOADSONGRESPONSE']._serialized_start=218
  _globals['_LOADSONGRESPONSE']._serialized_end=236
  _globals['_STARTSONGREQUEST']._serialized_start=238
  _globals['_STARTSONGREQUEST']._serialized_end=302
  _globals['_STARTSONGRESPONSE']._serialized_start=304
  _globals['_STARTSONGRESPONSE']._serialized_end=323
  _globals['_STOPSONGREQUEST']._serialized_start=325
  _globals['_STOPSONGREQUEST']._serialized_end=356
  _globals['_STOPSONGRESPONSE']._serialized_start=358
  _globals['_STOPSONGRESPONSE']._serialized_end=376
  _globals['_CLIENT']._serialized_start=379
  _globals['_CLIENT']._serialized_end=654
# @@protoc_insertion_point(module_scope)
