# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from Client.ClientGRPC import Client_pb2 as Client_dot_ClientGRPC_dot_Client__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in Client/ClientGRPC/Client_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClientStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CurrentState = channel.unary_unary(
                '/Client.Client/CurrentState',
                request_serializer=Client_dot_ClientGRPC_dot_Client__pb2.CurrentStateRequest.SerializeToString,
                response_deserializer=Client_dot_ClientGRPC_dot_Client__pb2.CurrentStateResponse.FromString,
                _registered_method=True)
        self.AddSong = channel.unary_unary(
                '/Client.Client/AddSong',
                request_serializer=Client_dot_ClientGRPC_dot_Client__pb2.AddSongRequest.SerializeToString,
                response_deserializer=Client_dot_ClientGRPC_dot_Client__pb2.AddSongResponse.FromString,
                _registered_method=True)
        self.DeleteSong = channel.unary_unary(
                '/Client.Client/DeleteSong',
                request_serializer=Client_dot_ClientGRPC_dot_Client__pb2.DeleteSongRequest.SerializeToString,
                response_deserializer=Client_dot_ClientGRPC_dot_Client__pb2.DeleteSongResponse.FromString,
                _registered_method=True)
        self.StartSong = channel.unary_unary(
                '/Client.Client/StartSong',
                request_serializer=Client_dot_ClientGRPC_dot_Client__pb2.StartSongRequest.SerializeToString,
                response_deserializer=Client_dot_ClientGRPC_dot_Client__pb2.StartSongResponse.FromString,
                _registered_method=True)
        self.PauseSong = channel.unary_unary(
                '/Client.Client/PauseSong',
                request_serializer=Client_dot_ClientGRPC_dot_Client__pb2.PauseSongRequest.SerializeToString,
                response_deserializer=Client_dot_ClientGRPC_dot_Client__pb2.PauseSongResponse.FromString,
                _registered_method=True)


class ClientServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CurrentState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CurrentState': grpc.unary_unary_rpc_method_handler(
                    servicer.CurrentState,
                    request_deserializer=Client_dot_ClientGRPC_dot_Client__pb2.CurrentStateRequest.FromString,
                    response_serializer=Client_dot_ClientGRPC_dot_Client__pb2.CurrentStateResponse.SerializeToString,
            ),
            'AddSong': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSong,
                    request_deserializer=Client_dot_ClientGRPC_dot_Client__pb2.AddSongRequest.FromString,
                    response_serializer=Client_dot_ClientGRPC_dot_Client__pb2.AddSongResponse.SerializeToString,
            ),
            'DeleteSong': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSong,
                    request_deserializer=Client_dot_ClientGRPC_dot_Client__pb2.DeleteSongRequest.FromString,
                    response_serializer=Client_dot_ClientGRPC_dot_Client__pb2.DeleteSongResponse.SerializeToString,
            ),
            'StartSong': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSong,
                    request_deserializer=Client_dot_ClientGRPC_dot_Client__pb2.StartSongRequest.FromString,
                    response_serializer=Client_dot_ClientGRPC_dot_Client__pb2.StartSongResponse.SerializeToString,
            ),
            'PauseSong': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseSong,
                    request_deserializer=Client_dot_ClientGRPC_dot_Client__pb2.PauseSongRequest.FromString,
                    response_serializer=Client_dot_ClientGRPC_dot_Client__pb2.PauseSongResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Client.Client', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Client.Client', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Client(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CurrentState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Client.Client/CurrentState',
            Client_dot_ClientGRPC_dot_Client__pb2.CurrentStateRequest.SerializeToString,
            Client_dot_ClientGRPC_dot_Client__pb2.CurrentStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Client.Client/AddSong',
            Client_dot_ClientGRPC_dot_Client__pb2.AddSongRequest.SerializeToString,
            Client_dot_ClientGRPC_dot_Client__pb2.AddSongResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Client.Client/DeleteSong',
            Client_dot_ClientGRPC_dot_Client__pb2.DeleteSongRequest.SerializeToString,
            Client_dot_ClientGRPC_dot_Client__pb2.DeleteSongResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Client.Client/StartSong',
            Client_dot_ClientGRPC_dot_Client__pb2.StartSongRequest.SerializeToString,
            Client_dot_ClientGRPC_dot_Client__pb2.StartSongResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Client.Client/PauseSong',
            Client_dot_ClientGRPC_dot_Client__pb2.PauseSongRequest.SerializeToString,
            Client_dot_ClientGRPC_dot_Client__pb2.PauseSongResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
