# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Server/ServerRoomGRPC/ServerRoomTime.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'Server/ServerRoomGRPC/ServerRoomTime.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*Server/ServerRoomGRPC/ServerRoomTime.proto\x12\x0eServerRoomTime\"\x11\n\x0fTimeSyncRequest\" \n\x10TimeSyncResponse\x12\x0c\n\x04time\x18\x01 \x01(\x01\x32_\n\x0eServerRoomTime\x12M\n\x08TimeSync\x12\x1f.ServerRoomTime.TimeSyncRequest\x1a .ServerRoomTime.TimeSyncResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Server.ServerRoomGRPC.ServerRoomTime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIMESYNCREQUEST']._serialized_start=62
  _globals['_TIMESYNCREQUEST']._serialized_end=79
  _globals['_TIMESYNCRESPONSE']._serialized_start=81
  _globals['_TIMESYNCRESPONSE']._serialized_end=113
  _globals['_SERVERROOMTIME']._serialized_start=115
  _globals['_SERVERROOMTIME']._serialized_end=210
# @@protoc_insertion_point(module_scope)
