# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ServerRoomMusic.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ServerRoomMusic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15ServerRoomMusic.proto\x12\x0fServerRoomMusic\"\x11\n\x0fKillRoomRequest\"\x12\n\x10KillRoomResponse\"\x15\n\x13\x43urrentStateRequest\"\x16\n\x14\x43urrentStateResponse\"\x10\n\x0e\x41\x64\x64SongRequest\"\x11\n\x0f\x41\x64\x64SongResponse\"\x13\n\x11\x44\x65leteSongRequest\"\x14\n\x12\x44\x65leteSongResponse\"\x12\n\x10PauseSongRequest\"\x13\n\x11PauseSongResponse\"\x15\n\x13MovePositionRequest\"\x16\n\x14MovePositionResponse2\x95\x04\n\x0fServerRoomMusic\x12O\n\x08KillRoom\x12 .ServerRoomMusic.KillRoomRequest\x1a!.ServerRoomMusic.KillRoomResponse\x12[\n\x0c\x43urrentState\x12$.ServerRoomMusic.CurrentStateRequest\x1a%.ServerRoomMusic.CurrentStateResponse\x12L\n\x07\x41\x64\x64Song\x12\x1f.ServerRoomMusic.AddSongRequest\x1a .ServerRoomMusic.AddSongResponse\x12U\n\nDeleteSong\x12\".ServerRoomMusic.DeleteSongRequest\x1a#.ServerRoomMusic.DeleteSongResponse\x12R\n\tPauseSong\x12!.ServerRoomMusic.PauseSongRequest\x1a\".ServerRoomMusic.PauseSongResponse\x12[\n\x0cMovePosition\x12$.ServerRoomMusic.MovePositionRequest\x1a%.ServerRoomMusic.MovePositionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ServerRoomMusic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KILLROOMREQUEST']._serialized_start=42
  _globals['_KILLROOMREQUEST']._serialized_end=59
  _globals['_KILLROOMRESPONSE']._serialized_start=61
  _globals['_KILLROOMRESPONSE']._serialized_end=79
  _globals['_CURRENTSTATEREQUEST']._serialized_start=81
  _globals['_CURRENTSTATEREQUEST']._serialized_end=102
  _globals['_CURRENTSTATERESPONSE']._serialized_start=104
  _globals['_CURRENTSTATERESPONSE']._serialized_end=126
  _globals['_ADDSONGREQUEST']._serialized_start=128
  _globals['_ADDSONGREQUEST']._serialized_end=144
  _globals['_ADDSONGRESPONSE']._serialized_start=146
  _globals['_ADDSONGRESPONSE']._serialized_end=163
  _globals['_DELETESONGREQUEST']._serialized_start=165
  _globals['_DELETESONGREQUEST']._serialized_end=184
  _globals['_DELETESONGRESPONSE']._serialized_start=186
  _globals['_DELETESONGRESPONSE']._serialized_end=206
  _globals['_PAUSESONGREQUEST']._serialized_start=208
  _globals['_PAUSESONGREQUEST']._serialized_end=226
  _globals['_PAUSESONGRESPONSE']._serialized_start=228
  _globals['_PAUSESONGRESPONSE']._serialized_end=247
  _globals['_MOVEPOSITIONREQUEST']._serialized_start=249
  _globals['_MOVEPOSITIONREQUEST']._serialized_end=270
  _globals['_MOVEPOSITIONRESPONSE']._serialized_start=272
  _globals['_MOVEPOSITIONRESPONSE']._serialized_end=294
  _globals['_SERVERROOMMUSIC']._serialized_start=297
  _globals['_SERVERROOMMUSIC']._serialized_end=830
# @@protoc_insertion_point(module_scope)
