# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Server/ServerLobbyGRPC/ServerLobby.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'Server/ServerLobbyGRPC/ServerLobby.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(Server/ServerLobbyGRPC/ServerLobby.proto\x12\x0bServerLobby\"$\n\x10JoinLobbyRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"8\n\x11JoinLobbyResponse\x12#\n\x06status\x18\x01 \x01(\x0e\x32\x13.ServerLobby.Status\"\x11\n\x0fGetRoomsRequest\"4\n\x10GetRoomsResponse\x12\r\n\x05rooms\x18\x01 \x03(\t\x12\x11\n\taddresses\x18\x02 \x03(\t\"5\n\x0fJoinRoomRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08roomname\x18\x02 \x01(\t\"7\n\x10JoinRoomResponse\x12#\n\x06status\x18\x01 \x01(\x0e\x32\x13.ServerLobby.Status\"6\n\x10LeaveRoomRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08roomname\x18\x02 \x01(\t\"8\n\x11LeaveRoomResponse\x12#\n\x06status\x18\x01 \x01(\x0e\x32\x13.ServerLobby.Status\" \n\x10StartRoomRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"Z\n\x11StartRoomResponse\x12#\n\x06status\x18\x01 \x01(\x0e\x32\x13.ServerLobby.Status\x12\r\n\x05rooms\x18\x02 \x03(\t\x12\x11\n\taddresses\x18\x03 \x03(\t*8\n\x06Status\x12\x0b\n\x07PENDING\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\t\n\x05MATCH\x10\x02\x12\t\n\x05\x45RROR\x10\x03\x32\x83\x03\n\x0bServerLobby\x12J\n\tJoinLobby\x12\x1d.ServerLobby.JoinLobbyRequest\x1a\x1e.ServerLobby.JoinLobbyResponse\x12G\n\x08GetRooms\x12\x1c.ServerLobby.GetRoomsRequest\x1a\x1d.ServerLobby.GetRoomsResponse\x12G\n\x08JoinRoom\x12\x1c.ServerLobby.JoinRoomRequest\x1a\x1d.ServerLobby.JoinRoomResponse\x12J\n\tLeaveRoom\x12\x1d.ServerLobby.LeaveRoomRequest\x1a\x1e.ServerLobby.LeaveRoomResponse\x12J\n\tStartRoom\x12\x1d.ServerLobby.StartRoomRequest\x1a\x1e.ServerLobby.StartRoomResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Server.ServerLobbyGRPC.ServerLobby_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=578
  _globals['_STATUS']._serialized_end=634
  _globals['_JOINLOBBYREQUEST']._serialized_start=57
  _globals['_JOINLOBBYREQUEST']._serialized_end=93
  _globals['_JOINLOBBYRESPONSE']._serialized_start=95
  _globals['_JOINLOBBYRESPONSE']._serialized_end=151
  _globals['_GETROOMSREQUEST']._serialized_start=153
  _globals['_GETROOMSREQUEST']._serialized_end=170
  _globals['_GETROOMSRESPONSE']._serialized_start=172
  _globals['_GETROOMSRESPONSE']._serialized_end=224
  _globals['_JOINROOMREQUEST']._serialized_start=226
  _globals['_JOINROOMREQUEST']._serialized_end=279
  _globals['_JOINROOMRESPONSE']._serialized_start=281
  _globals['_JOINROOMRESPONSE']._serialized_end=336
  _globals['_LEAVEROOMREQUEST']._serialized_start=338
  _globals['_LEAVEROOMREQUEST']._serialized_end=392
  _globals['_LEAVEROOMRESPONSE']._serialized_start=394
  _globals['_LEAVEROOMRESPONSE']._serialized_end=450
  _globals['_STARTROOMREQUEST']._serialized_start=452
  _globals['_STARTROOMREQUEST']._serialized_end=484
  _globals['_STARTROOMRESPONSE']._serialized_start=486
  _globals['_STARTROOMRESPONSE']._serialized_end=576
  _globals['_SERVERLOBBY']._serialized_start=637
  _globals['_SERVERLOBBY']._serialized_end=1024
# @@protoc_insertion_point(module_scope)
