# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Client.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'Client.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x43lient.proto\x12\x06\x43lient\"\x15\n\x13\x43urrentStateRequest\"\x16\n\x14\x43urrentStateResponse\"\x10\n\x0e\x41\x64\x64SongRequest\"\x11\n\x0f\x41\x64\x64SongResponse\"\x13\n\x11\x44\x65leteSongRequest\"\x14\n\x12\x44\x65leteSongResponse\"\x12\n\x10PauseSongRequest\"\x13\n\x11PauseSongResponse\"\x15\n\x13MovePositionRequest\"\x16\n\x14MovePositionResponse2\xe1\x02\n\x06\x43lient\x12I\n\x0c\x43urrentState\x12\x1b.Client.CurrentStateRequest\x1a\x1c.Client.CurrentStateResponse\x12:\n\x07\x41\x64\x64Song\x12\x16.Client.AddSongRequest\x1a\x17.Client.AddSongResponse\x12\x43\n\nDeleteSong\x12\x19.Client.DeleteSongRequest\x1a\x1a.Client.DeleteSongResponse\x12@\n\tPauseSong\x12\x18.Client.PauseSongRequest\x1a\x19.Client.PauseSongResponse\x12I\n\x0cMovePosition\x12\x1b.Client.MovePositionRequest\x1a\x1c.Client.MovePositionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Client_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CURRENTSTATEREQUEST']._serialized_start=24
  _globals['_CURRENTSTATEREQUEST']._serialized_end=45
  _globals['_CURRENTSTATERESPONSE']._serialized_start=47
  _globals['_CURRENTSTATERESPONSE']._serialized_end=69
  _globals['_ADDSONGREQUEST']._serialized_start=71
  _globals['_ADDSONGREQUEST']._serialized_end=87
  _globals['_ADDSONGRESPONSE']._serialized_start=89
  _globals['_ADDSONGRESPONSE']._serialized_end=106
  _globals['_DELETESONGREQUEST']._serialized_start=108
  _globals['_DELETESONGREQUEST']._serialized_end=127
  _globals['_DELETESONGRESPONSE']._serialized_start=129
  _globals['_DELETESONGRESPONSE']._serialized_end=149
  _globals['_PAUSESONGREQUEST']._serialized_start=151
  _globals['_PAUSESONGREQUEST']._serialized_end=169
  _globals['_PAUSESONGRESPONSE']._serialized_start=171
  _globals['_PAUSESONGRESPONSE']._serialized_end=190
  _globals['_MOVEPOSITIONREQUEST']._serialized_start=192
  _globals['_MOVEPOSITIONREQUEST']._serialized_end=213
  _globals['_MOVEPOSITIONRESPONSE']._serialized_start=215
  _globals['_MOVEPOSITIONRESPONSE']._serialized_end=237
  _globals['_CLIENT']._serialized_start=240
  _globals['_CLIENT']._serialized_end=593
# @@protoc_insertion_point(module_scope)
